name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # 匹配所有以v开头的tag
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create build directory
        run: mkdir -p dist/windows

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon=./icon.ico --add-data "icon.ico;." --name OllamaAIChat src/main.py

      - name: Move executable
        run: |
          move dist/OllamaAIChat.exe dist/windows/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OllamaAIChat-Windows
          path: dist/windows
          retention-days: 5

      - name: Generate Release Notes
        if: startsWith(github.ref, 'refs/tags/')
        id: release_notes
        run: |
          $version = "${{ github.ref_name }}"
          $changelog = Get-Content CHANGELOG.md -Raw
          $pattern = "## \[$version\].*?(?=## \[|$)"
          $match = [regex]::Match($changelog, $pattern, [System.Text.RegularExpressions.RegexOptions]::Singleline)
          if ($match.Success) {
              $notes = $match.Value
          } else {
              $notes = "## OllamaAIChat $version`n`n### 更新内容`n`n- 自动构建的Windows可执行文件`n- 运行环境：Windows 10/11"
          }
          $notes | Out-File release_notes.txt -Encoding UTF8

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/windows/OllamaAIChat.exe
          body_path: release_notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}