name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create build directory
        run: mkdir -p dist/windows

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon=./icon.ico --add-data "icon.ico;." --name OllamaAIChat src/main.py

      - name: Move executable
        run: |
          move dist/OllamaAIChat.exe dist/windows/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OllamaAIChat-Windows
          path: dist/windows
          retention-days: 5

  macos-build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create build directory
        run: mkdir -p dist/macos

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon=./icon.icns --add-data "icon.icns:." --name OllamaAIChat src/main.py

      - name: Move application
        run: |
          mv dist/OllamaAIChat.app dist/macos/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OllamaAIChat-macOS
          path: dist/macos
          retention-days: 5